embed_assets: off
gzip_assets: off
compress_assets: off
javascript_compressor: yui

javascripts:
  kakule:
    - public/javascripts/lib/*.js
    - public/javascripts/plugins/*.js
    - public/javascripts/kakule/init.js
    - public/javascripts/kakule/*.js
    - public/javascripts/kakule_start.js
    # - public/javascripts/application.js
    # - public/javascripts/*.js